[functions.export-etablissement-data]
verify_jwt = true

[functions.create-managed-user]
verify_jwt = true

[functions.resend-invitation]
verify_jwt = true

[functions.send-credentials]
verify_jwt = true

[functions.clean-orphan-auth]
verify_jwt = true

[functions.rappel-registre]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = true

[functions.check-trial-reminders]
verify_jwt = true

[functions.invite-user]
verify_jwt = true

[functions.send-signature-rappel]
verify_jwt = true

[functions.ia-assistant]
verify_jwt = true
